# Generated by Django 6.1 on 2026-08-13 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoniepointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Moniepoint POS Authorization API Key', max_length=255)),
                ('business_id', models.CharField(blank=True, help_text='POS Business ID', max_length=100)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook Secret Key for Signature Verification', max_length=255)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox / Testing'), ('PRODUCTION', 'Production / Live')], default='SANDBOX', max_length=20)),
                ('is_live_sync_enabled', models.BooleanField(default=True, help_text='Enable real-time background sync & webhook ingestion')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moniepoint API Configuration',
                'verbose_name_plural': 'Moniepoint API Configurations',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Bar POS #1', max_length=100)),
                ('serial_number', models.CharField(help_text='Moniepoint POS Serial Number', max_length=100, unique=True)),
                ('location_tag', models.CharField(default='Dining Area', help_text='e.g. Bar, Dining Room, Outdoor Patio, Takeout', max_length=100)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ONLINE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_event_id', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(default='V1_POS_TRANSACTION', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('signature_valid', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('moniepoint_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('terminal_serial', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN (Naira)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CARD_PURCHASE', 'Card Payment'), ('POS_TRANSFER', 'Bank Transfer'), ('USSD', 'USSD'), ('PAYCODE', 'PayCode'), ('ANY', 'Any / Multi')], default='CARD_PURCHASE', max_length=30)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'POS Purchase'), ('POS_TRANSFER', 'Transfer'), ('CARD_TRANSFER', 'Card Transfer'), ('BILL_PAYMENT', 'Bill Payment'), ('WITHDRAWAL', 'Withdrawal'), ('BOOM', 'Boom Payment')], default='PURCHASE', max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=20)),
                ('response_code', models.CharField(default='00', max_length=10)),
                ('response_message', models.CharField(default='Approved', max_length=255)),
                ('rrn', models.CharField(blank=True, max_length=100, null=True, verbose_name='RRN')),
                ('card_type', models.CharField(blank=True, help_text='e.g. Mastercard, Visa, Verve, Transfer', max_length=50)),
                ('masked_pan', models.CharField(blank=True, help_text='e.g. 5399****1234', max_length=30)),
                ('customer_name', models.CharField(blank=True, help_text='Customer or Table Note', max_length=150)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
